# Generated by Django 5.2.7 on 2026-01-27 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('face', 'Face'), ('retina', 'Retina')], max_length=20)),
                ('image_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='attendance_app.trainingdataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biometric_samples',
                'ordering': ['-created_at'],
            },
        ),
    ]
