# Generated by Django 6.0.1 on 2026-03-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_user_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the camera', max_length=200)),
                ('location', models.CharField(help_text='Physical location of the camera', max_length=255)),
                ('camera_url', models.TextField(help_text='Camera URL/Stream or device ID')),
                ('camera_type', models.CharField(choices=[('usb', 'USB Camera'), ('ip', 'IP Camera'), ('rtsp', 'RTSP Stream')], default='usb', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this camera')),
                ('resolution_width', models.IntegerField(default=640, help_text='Camera resolution width in pixels')),
                ('resolution_height', models.IntegerField(default=480, help_text='Camera resolution height in pixels')),
                ('fps', models.IntegerField(default=30, help_text='Frames per second')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cameras',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='data_file',
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.subject'),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='image_path',
            field=models.ImageField(default='', help_text='Path to biometric image', upload_to='biometric/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recognition_type',
            field=models.CharField(choices=[('face', 'Face Recognition'), ('retina', 'Retina Recognition'), ('manual', 'Manual Entry')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='biometricsample',
            name='sample_type',
            field=models.CharField(choices=[('face', 'Face Sample'), ('retina', 'Retina Sample')], max_length=20),
        ),
        migrations.AlterField(
            model_name='biometricsample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingdataset',
            name='dataset_type',
            field=models.CharField(choices=[('face', 'Face Recognition'), ('retina', 'Retina Recognition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
