# Generated by Django 6.0.1 on 2026-03-16 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_camera_remove_biometricdata_data_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='attendance_app.subject')),
            ],
            options={
                'db_table': 'live_attendance_sessions',
            },
        ),
    ]
