# Generated by Django 5.2.7 on 2026-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0008_department_subject_department_user_dept_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked automatically when a student self-marks via biometric. Locked records cannot be edited or overridden.'),
        ),
    ]
